### ISSUE TITLE
Issues with the action

### ISSUE THREAD

**Issue by marcelfarres** [lucasruy/sync-branch-action#25]
Hi! 

First of all thanks for creating this action, is exactly what I need and it will be so useful :) 

I started using it today and even on the first run and using default parameters this happened: 

```
Run LucasRuy/sync-branch-action@v1.1.0
  with:
    GITHUB_TOKEN: ***
    SOURCE_BRANCH: master
    DESTINATION_BRANCH: AT-MRI
Starting process to make a new pull request...
Verifying if required fields is setted.
Verifying if already exist opened pull request.
A pull request has already been opened to update the AT-MRI branch
```

Here is my yml file just in case I missed something very obvious. 

```
name: Auto-PR-to-active-testing-branches

# Controls when the workflow will run on:

on:
  push:
    branches:
      - master

jobs:
  at-updates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup environment
        uses: actions/checkout@v2

      - name: Create update pull request
        uses: LucasRuy/sync-branch-action@v1.1.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SOURCE_BRANCH: 'master'
          DESTINATION_BRANCH: 'AT-MRI'
#           PULL_REQUEST_TITLE: 'Sync: keep branch MRI updated master'
#           PULL_REQUEST_BODY: 'Check that nothing is terribly wrong, if not merge.'
```

Thanks in advance :) have a good day/week!
